{% set name = "faim-ipa" %}
{% set version = "0.11.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/faim_ipa-{{ version }}.tar.gz
  sha256: 444a6333d8924f58eaad16b460d9685adc6171e34e741f042ea71110c323dd87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - defusedxml
    - distributed
    - matplotlib-base
    - numpy <2
    - ome-zarr
    - pandas
    - pint
    - pydantic >=2
    - questionary
    - scikit-image
    - tqdm

test:
  imports:
    - faim_ipa
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/fmi-faim/faim-ipa
  summary: Tools used at FMI-FAIM for Image Processing and Analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - imagejan
    - tibuch
