schema_version: 1

context:
  name: faim-ipa
  version: 0.13.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/faim_ipa-${{ version }}.tar.gz
  sha256: 3cb05909dbeba2f22f4f87c63399b1aa80136d14101256a8f76fe7b33d72f6b5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - defusedxml
    - distributed
    - matplotlib-base
    - numpy
    - ome-zarr
    - pandas
    - pint
    - pydantic >=2
    - questionary
    - scikit-image
    - tqdm

tests:
  - python:
      imports:
        - faim_ipa
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Tools used at FMI-FAIM for Image Processing and Analysis.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/fmi-faim/faim-ipa

extra:
  recipe-maintainers:
    - imagejan
    - tibuch
